language: android

jdk:
- oraclejdk8

android:
  components:
    - CMake
    - build-tools-25.0.2
    - android-25

before_install:
- git clone --depth 1 https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
- export ANDROID_NDK_HOME=$HOME/android-ndk-root
